package clover

var (
	errParseURI                 = NewRespErr(400, "invalid_uri", "Invalid parse uri")
	errOnlyOneTokenMethod       = NewRespErr(400, "invalid_request", "Only one method may be used to authenticate at a time (Auth header, GET or POST)")
	errNoTokenInRequest         = NewRespErr(400, "invalid_request", "No access token in request")
	errMalFormedHeader          = NewRespErr(400, "invalid_request", "Malformed auth header")
	errCredentailsRequired      = NewRespErr(400, "invalid_client", "Client credentials are required")
	errCredentailsNotInBody     = NewRespErr(400, "invalid_client", "Client credentials were not found in the body")
	errInvalidAuthMSG           = NewRespErr(400, "invalid_client", "Invalid authorization message")
	errInvalidAuthHeader        = NewRespErr(400, "invalid_client", "Invalid authorization header")
	errUserDeniedAccess         = NewRespErr(403, "access_denied", "The user denied access to your application")
	errNoClientID               = NewRespErr(400, "invalid_client", "No client id supplied")
	errInvalidClientID          = NewRespErr(400, "invalid_client", "The client id supplied is invalid")
	errStateRequired            = NewRespErr(400, "invalid_request", "The state parameter is required")
	errRedirectMismatch         = NewRespErr(400, "redirect_uri_mismatch", "The redirect URI provided is missing or does not match")
	errNoRedirectURI            = NewRespErr(400, "invalid_uri", "No redirect URI was supplied or stored")
	errInvalidRespType          = NewRespErr(400, "invalid_request", "Invalid or missing response type")
	errUnSupportedImplicit      = NewRespErr(400, "unsupported_response_type", "implicit grant type not supported")
	errUnAuthorizedGrant        = NewRespErr(400, "unauthorized_client", "The grant type is unauthorized for this client_id")
	errCodeUnSupportedGrant     = NewRespErr(400, "unsupported_response_type", "authorization code grant type not supported")
	errUnSupportedScope         = NewRespErr(400, "invalid_scope", "An unsupported scope was requested")
	errNoScope                  = NewRespErr(400, "invalid_client", "This application requires you specify a scope parameter")
	errMustBePostMetthod        = NewRespErr(400, "invalid_request", "The request method must be POST when requesting an access token")
	errGrantTypeRequired        = NewRespErr(400, "invalid_request", "The grant type was not specified in the request")
	errUnSupportedGrantType     = NewRespErr(400, "unsupported_grant_type", "Grant type not supported")
	errInvalidScopeRequest      = NewRespErr(400, "invalid_scope", "The scope requested is invalid for this request")
	errInvalidScopeClient       = NewRespErr(400, "invalid_scope", "The scope requested is invalid for this client")
	errUsernamePasswordRequired = NewRespErr(400, "invalid_request", "Username and password are required")
	errInvalidClientCredentail  = NewRespErr(400, "invalid_grant", "Invalid Client credential")
	errRefreshTokenRequired     = NewRespErr(400, "invalid_request", "Missing parameter: refresh_token is required")
	errRefreshTokenExpired      = NewRespErr(400, "invalid_grant", "Refresh token has expired")
	errInvalidRefreshToken      = NewRespErr(400, "invalid_grant", "Invalid refresh token")
	errCodeRequired             = NewRespErr(400, "invalid_request", "Missing parameter: code is required")
	errAuthCodeNotExist         = NewRespErr(400, "invalid_grant", "Authorization code doesn't exist or is invalid for the client")
	errAuthCodeExpired          = NewRespErr(400, "invalid_grant", "The authorization code has expired")
	errAssetionRequired         = NewRespErr(400, "invalid_request", "Missing parameter: assertion is required")
	errInvalidAccessToken       = NewRespErr(400, "invalid_token", "The access token provided is invalid")
	errAccessTokenExpired       = NewRespErr(400, "expired_token", "The access token provided has expired")
	errInsufficientScope        = NewRespErr(403, "insufficient_scope", "The request requires higher privileges than provided by the access token")
)

func errInternal(desc string) *Response {
	return NewRespErr(500, "internal", desc)
}
