package mocks

import clover "github.com/plimble/clover"
import mock "github.com/stretchr/testify/mock"

// ClientStorage is an autogenerated mock type for the ClientStorage type
type ClientStorage struct {
	mock.Mock
}

// GetClient provides a mock function with given fields: id
func (_m *ClientStorage) GetClient(id string) (*clover.Client, error) {
	ret := _m.Called(id)

	var r0 *clover.Client
	if rf, ok := ret.Get(0).(func(string) *clover.Client); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clover.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClientWithSecret provides a mock function with given fields: id, secret
func (_m *ClientStorage) GetClientWithSecret(id string, secret string) (*clover.Client, error) {
	ret := _m.Called(id, secret)

	var r0 *clover.Client
	if rf, ok := ret.Get(0).(func(string, string) *clover.Client); ok {
		r0 = rf(id, secret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clover.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
