package mocks

import clover "github.com/plimble/clover"
import mock "github.com/stretchr/testify/mock"

// OAuth2 is an autogenerated mock type for the OAuth2 type
type OAuth2 struct {
	mock.Mock
}

// RegisterGrantType provides a mock function with given fields: grant
func (_m *OAuth2) RegisterGrantType(grant clover.GrantType) {
	_m.Called(grant)
}
