package mocks

import mock "github.com/stretchr/testify/mock"

// ScopeValidator is an autogenerated mock type for the ScopeValidator type
type ScopeValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: requestScopes, clientScopes
func (_m *ScopeValidator) Validate(requestScopes []string, clientScopes []string) ([]string, error) {
	ret := _m.Called(requestScopes, clientScopes)

	var r0 []string
	if rf, ok := ret.Get(0).(func([]string, []string) []string); ok {
		r0 = rf(requestScopes, clientScopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, []string) error); ok {
		r1 = rf(requestScopes, clientScopes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
