package mocks

import mock "github.com/stretchr/testify/mock"

// TokenGenerator is an autogenerated mock type for the TokenGenerator type
type TokenGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields: clientID, userID, scope, tokenLifespan
func (_m *TokenGenerator) Generate(clientID string, userID string, scope string, tokenLifespan int) (string, error) {
	ret := _m.Called(clientID, userID, scope, tokenLifespan)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, string, int) string); ok {
		r0 = rf(clientID, userID, scope, tokenLifespan)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, int) error); ok {
		r1 = rf(clientID, userID, scope, tokenLifespan)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
