package mocks

import clover "github.com/plimble/clover"
import mock "github.com/stretchr/testify/mock"

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: username, password
func (_m *UserService) GetUser(username string, password string) (*clover.User, error) {
	ret := _m.Called(username, password)

	var r0 *clover.User
	if rf, ok := ret.Get(0).(func(string, string) *clover.User); ok {
		r0 = rf(username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clover.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
