package mocks

import clover "github.com/plimble/clover"
import mock "github.com/stretchr/testify/mock"

// ClientStorage is an autogenerated mock type for the ClientStorage type
type ClientStorage struct {
	mock.Mock
}

// DeleteClient provides a mock function with given fields: id
func (_m *ClientStorage) DeleteClient(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetClient provides a mock function with given fields: id
func (_m *ClientStorage) GetClient(id string) (clover.Client, error) {
	ret := _m.Called(id)

	var r0 clover.Client
	if rf, ok := ret.Get(0).(func(string) clover.Client); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(clover.Client)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveClient provides a mock function with given fields: client
func (_m *ClientStorage) SaveClient(client *clover.Client) error {
	ret := _m.Called(client)

	var r0 error
	if rf, ok := ret.Get(0).(func(*clover.Client) error); ok {
		r0 = rf(client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
