package mocks

import clover "github.com/plimble/clover"
import mock "github.com/stretchr/testify/mock"

// ScopeStorage is an autogenerated mock type for the ScopeStorage type
type ScopeStorage struct {
	mock.Mock
}

// CreateScope provides a mock function with given fields: scope
func (_m *ScopeStorage) CreateScope(scope *clover.Scope) error {
	ret := _m.Called(scope)

	var r0 error
	if rf, ok := ret.Get(0).(func(*clover.Scope) error); ok {
		r0 = rf(scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteScope provides a mock function with given fields: id
func (_m *ScopeStorage) DeleteScope(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllScope provides a mock function with given fields:
func (_m *ScopeStorage) GetAllScope() ([]*clover.Scope, error) {
	ret := _m.Called()

	var r0 []*clover.Scope
	if rf, ok := ret.Get(0).(func() []*clover.Scope); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*clover.Scope)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
