package mocks

import mock "github.com/stretchr/testify/mock"
import scope "github.com/plimble/clover/scope"

// ScopeStorage is an autogenerated mock type for the ScopeStorage type
type ScopeStorage struct {
	mock.Mock
}

// CreateScope provides a mock function with given fields: _a0
func (_m *ScopeStorage) CreateScope(_a0 *scope.Scope) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*scope.Scope) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteScope provides a mock function with given fields: id
func (_m *ScopeStorage) DeleteScope(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllScope provides a mock function with given fields:
func (_m *ScopeStorage) GetAllScope() ([]*scope.Scope, error) {
	ret := _m.Called()

	var r0 []*scope.Scope
	if rf, ok := ret.Get(0).(func() []*scope.Scope); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*scope.Scope)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
